<?php namespace Ventamatic\Core\Branch;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;
use Exception;
use Ventamatic\Core\Product\Product;
use Ventamatic\Core\System\RevisionableBaseModel;
use Ventamatic\Core\External\Supplier;
use Ventamatic\Core\User\User;

class Buy extends RevisionableBaseModel
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $softDelete = true;

    protected $fillable = ['id', 'payment_type_id', 'card_payment_id', 'iva',
        'ieps', 'total', 'user_id', 'supplier_id', 'branch_id',
        'supplier_bill_id'];

    protected $casts = [
        'id' => 'integer',
        'payment_type_id' => 'integer',
        'user_id' => 'integer',
        'supplier_id' => 'integer',
        'branch_id' => 'integer',
        'card_payment_id' => 'integer',
        'iva' => 'double',
        'ieps' => 'double',
        'total' => 'double',
    ];

    public function branch()
    {
        return $this->belongsTo(Branch::class);
    }

    public function paymentType()
    {
        return $this->belongsTo(PaymentType::class);
    }

    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class)
            ->withPivot('cost','quantity', 'inventory_movement_type_id');
    }

    public function inventoryMovements()
    {
        return $this->morphMany(InventoryMovement::class, 'inventoriableMovement');
    }

    public function newPivot(Model $parent, array $attributes, $table, $exists, $using = null)
    {
        if ($parent instanceof Product) {
            return new BuyProductPivot($parent, $attributes, $table, $exists);
        }

        return parent::newPivot($parent, $attributes, $table, $exists, $using); // TODO: Change the autogenerated stub
    }


    public static function doBuy(User $user,
                                 $supplier,
                                 $supplierBillId,
                                 Branch $branch,
                                 PaymentType $paymentType,
                                 Array $products,
                                 $ieps, $iva, $total,
                                 $supplierBillTotal,
                                 $card_payment_id = null)
    {
        $buy = new self();
        $buy->supplier()->associate($supplier);
        $buy->user()->associate($user);
        $buy->branch()->associate($branch);
        $buy->paymentType()->associate($paymentType);

        $buy->card_payment_id = $card_payment_id;
        $buy->total = $total;
        $buy->ieps = $ieps;
        $buy->iva = $iva;
        $buy->supplier_bill_id = $supplierBillId;
        $buy->supplier_bill_total = $supplierBillTotal;

        try {
            DB::beginTransaction();

            $buy->save();
            $calculatedTotal = $buy->attachProducts($products, $branch, $user);
            self::validateTotal($total, $calculatedTotal);

            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
            throw $e;
        }

        return $buy;
    }

    private static function validateTotal($given_total, $calculated_total) {
        if($given_total != floor($calculated_total*100)/100){
            throw new Exception(\Lang::get('buy.total_not_match', [
                'given_total' => $given_total,
                'calculed_total' => $calculated_total,
            ]));
        }
    }

    private function attachProducts(Array $products, Branch $branch, User $user)
    {
        $total = 0;
        $batch = InventoryMovement::getLastBatch();

        foreach ($products as $productData) {
            /** @var Product $product */
            $product = Product::findOrFail($productData['product_id']);
            $cost = $productData['cost'];
            $quantity = $productData['quantity'];
            $inventory_movement_type_id = $productData['inventory_movement_type_id'];

            $total += $cost * $quantity;

            $this->products()->attach($product->id, compact(
                'cost',
                'quantity',
                'inventory_movement_type_id'
            ));

            $branch->addInventoryMovement($user, $product, [
                'inventory_movement_type_id' => $inventory_movement_type_id,
                'quantity' => $productData['quantity'],
                'value' => $productData['cost'],
                'model' => $this,
                $batch
            ]);
        }

        return $total;
    }


}
